blank_issues_enabled: false
contact_links:
  - name: Aevoa Studios Moderative Help
    url: https://aevoa.tech/
    about: Please create a ticket here if you need help with the platform
  - name: Aevoa Studios Support Discord
    url: https://discord.gg/vuEZJTj9
    about: For any other questions